#pragma once
#ifndef AE2F_PRINTER_ENUM_METHOD
#define AE2F_PRINTER_ENUM_METHOD

enum ae2f_Printer_Method {
	AE2F_PRINTER_M_CONTAINER_STRING = 0,
	AE2F_PRINTER_M_CONTAINER_NUMBERS = 1
};

#endif // !AE2F_PRINTER_ENUM_METHOD
