#pragma once
#ifndef AE2F_PRINTER_ENUM_OFF
#define AE2F_PRINTER_ENUM_OFF

enum ae2f_Printer_Off {
	AE2F_PRINTER_CONTAINER_DYNAMIC = 0,
	AE2F_PRINTER_CONTAINER_PAIR = 3,
	AE2F_PRINTER_CONTAINER_MAP = 5
};

#endif // !AE2F_PRINTER_ENUM_OFF
